console.log(`Hii! this is Muna's first code`)
console.log(`yo mero second code`)
console.log(`yo mero 3rd code`)
console.log("Pooja le change garexin hai")
console.log("pabin le gareko change")
console.log("muna")
console.log("hii pabin")